### ISSUE TITLE
Feature: Display current video bit rate in User Interface

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/rt-5gms-application#22]
# Feature description

As a demonstrator of the 5GMS-Aware Application, I would like to know which video representation is currently playing back.

The application should display the bit rate (and, if available, the representation ID string) of the currently selected video representation as part of the User Interface. This would ideally be overlaid on a corner of the rendered video window, or else somewhere nearby.

**Comment by dsilhavy** [comment]
This feature request has been implemented in:

* https://github.com/5G-MAG/rt-5gms-application/pull/23
* https://github.com/5G-MAG/rt-5gms-common-android-library/pull/18
* https://github.com/5G-MAG/rt-5gms-media-stream-handler/pull/48

To avoid polling the M7 interface every few seconds to get the currently selected Representation a pub/sub approach has been implemented. The MediaStreamHandler dispatches a notification to all subscribers once the Representation has changed. In this case, the 5GMSd Aware Application is the only subscriber. It uses the payload of the notification that includes an instance of [MediaLoadData](https://developer.android.com/reference/androidx/media3/exoplayer/source/MediaLoadData) to update the overlay in the UI. The final result looks the following:

<img width="760" alt="Bildschirmfoto 2023-08-16 um 08 48 08" src="https://github.com/5G-MAG/rt-5gms-application/assets/2427039/85b8a4cd-b4da-4939-9441-932a00ad614f">

**Comment by rjb1000** [comment]
Looks great, @dsilhavy. Thanks!

**Comment by dsilhavy** [comment]
Released in version 1.0.2
