### ISSUE TITLE
Initialize() not called even after requetsting and getting the permission

### ISSUE THREAD

**Issue by shilinding** [5G-MAG/rt-5gms-application#34]
**Description**
For requestUserPermissions(),  the initialize() is only called when the permission has been granted.
If not granted, it will request the permission, and even after get the permission,  the initialize() still won't be called, the program will run without initializing .

```
    private fun requestUserPermissions() {
        val requestPermissionLauncher =
            registerForActivityResult(
                ActivityResultContracts.RequestPermission()
            ) { _: Boolean ->
                initialize()
            }

        // Register the cell info callback
        if (ActivityCompat.checkSelfPermission(
                this,
                Manifest.permission.ACCESS_FINE_LOCATION
            ) != PackageManager.PERMISSION_GRANTED
        ) {
            requestPermissionLauncher.launch(
                Manifest.permission.ACCESS_FINE_LOCATION
            )
        } else {
            initialize()
        }
    }
```

**Suggestion**
After requetsting the permission,  check permission again.  If get, call the initialize().

**Comment by dsilhavy** [comment]
There is a call to `initialize` in `registerForActivityResult`. If the permission was already set we end up in the else block:

````
else {
            initialize()
        }
````

If the permission needs to be requested we end up in the callback function and initialize is called regardless of the `_` boolean value:

````
          ActivityResultContracts.RequestPermission()
            ) { _: Boolean ->
                initialize()
            }
````

Under which condition did you observe `initialize` not being called?

**Comment by shilinding** [comment]
I didn't notice that `ActivityResultContracts.RequestPermission()` will always  call `initialize` . Then it should be OK.

But when permission needs to be requested,  and asks the user for permission, but the user deny.  Do we still want `initialize()` to be called unconditionally and go ahead?

**Comment by dsilhavy** [comment]
> But when permission needs to be requested, and asks the user for permission, but the user deny. Do we still want `initialize()` to be called unconditionally and go ahead?

Yes, because playback will still work, only the `location` property of the consumption report will have no useful value.
